### ISSUE TITLE
Repurposed Structures for 1.18.1 keeps crashing when ever i try to generate a new world

### ISSUE THREAD

**Issue by justawander** [TelepathicGrunt/RepurposedStructures#207] opened 2022-05-30 19:27 UTC
https://bytebin.lucko.me/ODDiz9QphH

**Comment by TelepathicGrunt** [comment] 2022-05-30 20:58
Just fyi, I only dev on latest released Mc versions to reduce my workload so 1.18.1 is unsupported by me rn.

That aside, the error you shown looks like the starting template pool used for one of rs’s structures died or failed to be parsed for whatever reason. Without the full latest.log file, there’s really no way to even guess what could even be the cause or why the file failed to be parsed.

**Comment by TelepathicGrunt** [comment] 2022-06-07 14:30
Closing as it has been a week and no additional info was provided

**Closed as completed by TelepathicGrunt** 2022-06-07 14:30 UTC
Labels: Unsupported version
