### ISSUE TITLE
World crash

### ISSUE THREAD

**Issue by avescarelo** [TelepathicGrunt/RepurposedStructures#296] opened 2023-08-12 19:31 UTC
Hey!
I was found a problem with world:
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/26678843/69411f74-46e0-4837-909c-2e729dc800cd)

Also, log: https://gist.github.com/avescarelo/ce8c1f4b1c76bd552a471d95569d2160

MC version: 1.20.1
Mod version: 7.0.0+1.20-forge

**Comment by avescarelo** [comment] 2023-08-12 19:33
Crash report: https://gist.github.com/avescarelo/df42a65a11fda2d5e5e88b84da51012e

**Comment by TelepathicGrunt** [comment] 2023-08-12 20:18
Are you using the absolute latest version of Waystone mod with repurposed structures

**Comment by TelepathicGrunt** [comment] 2023-08-12 20:18
I clicked wrong button. Fun

**Comment by avescarelo** [comment] 2023-08-12 20:20
> Are you using the absolute latest version of Waystone mod with repurposed structures

I use `waystones-forge-1.20-14.0.1`, it's latest right

**Comment by TelepathicGrunt** [comment] 2023-08-12 20:21
Your log link shows a server deadlock which is entirely different than the first image you showed. Not at all related to each other. Please put on FullStackWatchdog mod and reproduce the server deadlock crash. Then share the server latest.log afterwards. That FullStackWatchdog will print more info out that will make diagnosing the server deadlock easier

**Comment by avescarelo** [comment] 2023-08-12 20:28
> Your log link shows a server deadlock which is entirely different than the first image you showed. Not at all related to each other. Please put on FullStackWatchdog mod and reproduce the server deadlock crash. Then share the server latest.log afterwards. That FullStackWatchdog will print more info out that will make diagnosing the server deadlock easier

Sorry, what about this?
log: https://gist.github.com/avescarelo/01769280749e8740a0325fb3c1bf85ef
crashrepot: https://gist.github.com/avescarelo/8870ce76c4858d385bcc9ff33d188bdf

**Comment by TelepathicGrunt** [comment] 2023-08-12 21:48
```
[12àâã.2023 23:26:01.019] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Avescarelo issued server command: /locate structure #ctov:village_mushroom
[12àâã.2023 23:27:01.037] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[12àâã.2023 23:27:01.037] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
```

You tried to locate a ChoiceTheorem's Overhauled Village's mushroom village but the game took too long to find it. Possible due to mushroom biomes not spawning in your world or is too rare. This has nothing to do with Repurposed Structures as far as I can see

**Comment by avescarelo** [comment] 2023-08-12 21:50
Oh, thsnk you

**Comment by TelepathicGrunt** [comment] 2023-08-13 22:15
Yeah this seems to be  ChoiceTheorem's Overhauled Village issue. 

I doubled checked the waystone thing and was able to find a waystone in my birch village with both mods on so it seems to be fine
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/8017c4be-c549-4220-98df-06ca343a0cd5)

I'll close this issue report for now

**Closed as completed by TelepathicGrunt** 2023-08-13 22:15 UTC
Labels: Another mod's issue
