### ISSUE TITLE
Game Crashes when obtaining Jungle Explorer Map from Cartographer

### ISSUE THREAD

**Issue by PacoDaPea** [TelepathicGrunt/RepurposedStructures#304] opened 2023-10-06 06:42 UTC
I don't think this is a vanilla feature, and this mod is the only one I'm using that completely overhauls vanilla structures, so I can only assume that the jungle explorer map came from here.
But yeah, when I bought it from the cartographer, the game freezes and soon crashes.
Granted I have plenty of mods installed, albeit most aren't really big, so there's a good chance that something was incompatible for this to happen.
Kinda locked me out of the world too. Attempting to reopen the world just boots me back to the launcher. Good thing I made backups!
Here's the crash log.
[crash-2023-10-06_14.02.15-client.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/12827722/crash-2023-10-06_14.02.15-client.txt)

UPDATE: Now it happens when I buy an ocean explorer map too!

**Comment by TelepathicGrunt** [comment] 2023-10-06 12:17
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method getTextMipMap(Lnet/minecraft/resources/ResourceLocation;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Lnet/minecraft/client/renderer/RenderType; in moonlight-common.mixins.json:MapInstanceMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap moonlight-common-refmap.json`

Moonlight Lib appears to have a mixin that is crashing on explorer maps. 

You're using moonlight-1.20-2.8.38. Their mod page says they refactored their map code in moonlight-1.20-2.8.45. Update that mod and supplementaries. If the crash still happens, report the issue to Moonlight Lib 
https://www.curseforge.com/minecraft/mc-mods/selene/files/4783825

**Comment by TelepathicGrunt** [comment] 2023-10-13 00:53
Closing since this appears to be an outdated moonlight issue. Not a Repurposed Structures issue

**Closed as completed by TelepathicGrunt** 2023-10-13 00:53 UTC
Labels: Another mod's issue
