### ISSUE TITLE
Dirt Path Crash

### ISSUE THREAD

**Issue by Reshy** [TelepathicGrunt/RepurposedStructures#154] opened 2021-11-09 06:51 UTC
**Caused by: java.lang.RuntimeException: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:dirt_path' at position 0: <--[HERE]**
	at net.minecraft.world.gen.feature.template.JigsawReplacementStructureProcessor.func_230386_a_(SourceFile:37) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.StructureProcessor.process(StructureProcessor.java:18) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.gen.feature.template.Template.processBlockInfos(Template.java:378) ~[?:?] **{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:structures.TemplateAccessor,pl:mixin:APP:quark.mixins.json:TemplateMixin,pl:mixin:A}**
	at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:222) ~[?:?] **{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:structures.TemplateAccessor,pl:mixin:APP:quark.mixins.json:TemplateMixin,pl:mixin:A}**
	at net.minecraft.world.gen.feature.jigsaw.SingleJigsawPiece.func_230378_a_(SingleJigsawPiece.java:106) ~[?:?] **{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:structures.SingleJigsawPieceAccessor,pl:mixin:APP:repurposed_structures.mixins.json:structures.CharmSingleJigsawPieceMixin,pl:mixin:APP:charm.mixins.json:SingleJigsawPieceMixin,pl:mixin:A}**
	at net.minecraft.world.gen.feature.structure.AbstractVillagePiece.func_237001_a_(SourceFile:83) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.gen.feature.structure.AbstractVillagePiece.func_230383_a_(SourceFile:79) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.gen.feature.structure.StructureStart.func_230366_a_(StructureStart.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:StructureStartMixin,pl:mixin:A}
	at net.minecraft.world.biome.Biome.lambda$generate$20(Biome.java:234) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:BiomeMixin,pl:mixin:APP:chocolate.mixins.json:world.biome.BiomeMixin,pl:mixin:APP:terraincognita.mixins.json:client.BiomeMixin,pl:mixin:APP:byg.mixins.json:access.BiomeAccess,pl:mixin:A}

[crash-2021-11-08_22.37.54-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/7502578/crash-2021-11-08_22.37.54-server.txt)

**Comment by TelepathicGrunt** [comment] 2021-11-09 12:11
@Reshy are you using the more villager datapack? If so, you may be using an older version that was crashing. https://github.com/TelepathicGrunt/RepurposedStructures/issues/153

Delete that datapack and redownload v2 of the datapack from here and let me know if that resolves the issue: https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.8

if so, I’ll close this bug report

**Comment by TelepathicGrunt** [comment] 2021-11-09 12:13
Actually hmm, that datapack crashed on a mushroom stem typo. Not dirt block. Can you show me all the datapacks you’re using? I’ll also run my mod’s nbt files through a script to see if the current version has mentions of the dirt path somewhere (which should be grass path but 1.17 renamed it which causes these kinds of mistakes by me) 

If you can reproduce the crash easily, can you put on this mod called Blame, get the crash, and post the latest.log file here? Blame will tell me which structure and the piece is the issue
https://www.curseforge.com/minecraft/mc-mods/blame

Edit: script ran through my mod's internal structure pieces and none had dirt path in them. Gonna check my datapacks listed on my github now

**Comment by TelepathicGrunt** [comment] 2021-11-09 12:48
And now I ran the script on all my datapacks and could't find dirt path anywhere. Yeah i think you are using an outdated datapack or the issue is with another mod's structure. Delete and redownload all the datapacks you use from my github to rule out any outdated repurposed structures datapack: https://github.com/TelepathicGrunt/RepurposedStructures/releases

If the issue still persist, run with Blame on, get the crash, and share latest.log and from there, we can narrow down which datapack or mod could be the issue.

**Comment by TelepathicGrunt** [comment] 2021-11-16 20:59
It's been a week and no other person seemed to have reported this issue and no extra info was provided. There's nothing more I can do without additional info and being unable to reproduce the issue myself. So I'll close this issue report now but I'll re-open once I get a latest.log of the crash with Blame on.

**Closed as completed by TelepathicGrunt** 2021-11-16 20:59 UTC
Labels: need more info
