### ISSUE TITLE
Crash with BloodMagic

### ISSUE THREAD

**Issue by Darkfiend009** [TelepathicGrunt/RepurposedStructures#70] opened 2021-03-20 13:47 UTC
Minecraft 1.16.5
Forge: 36.1.0
Repurposed Structures: 2.5.1

Crash Report: https://pastebin.com/E7m0kSzb

Client crash in single player when entering a world for the first time. I have also reported this to the Terraforged issue tracker just in case it's on that side.

**Comment by TelepathicGrunt** [comment] 2021-03-20 16:10
Actually, this isn’t caused by terraforged nor repurposed structures. It’s seem BloodMagic has a GlobalLootModifier that crashes when certain mobs are spawned with villages. Since my villages contains vanilla mobs (Villagers, Cats, and Iron Golems), this crash would also happen in vanilla villages too. If you haven’t reported to BloodMagic yet, I can contact them soon

**Comment by TelepathicGrunt** [comment] 2021-03-20 16:59
Ah looks like BloodMagic does know about the issue. It seems to be a conflict of them with another mod that possibly modifies entity loot. Weird stuff. keep watch for BloodMagic's next update as they will be fixing it soon!
https://github.com/WayofTime/BloodMagic/issues/1795

**Comment by Darkfiend009** [comment] 2021-03-20 17:11
Thank you!

**Comment by TelepathicGrunt** [comment] 2021-07-25 15:07
BloodMagic-1.16.4-3.1.1-16 just released yesterday and I think this fixed this crash. I'll close this report now

**Closed by TelepathicGrunt** 2021-07-25 15:07 UTC
Labels: Mod Compat
