### ISSUE TITLE
Server Crash upon loading new structures

### ISSUE THREAD

**Issue by LunafeyLazuli** [TelepathicGrunt/RepurposedStructures#107] opened 2021-06-13 23:39 UTC
It's happened 3 times since last night when we updated to the latest version, but it seems that when players are running around exploring new chunks, something happens when it tries to generate a new structure and then the server crashes https://pastebin.com/mvh25wGU

**Comment by TelepathicGrunt** [comment] 2021-06-14 00:17
Can you put on Blame https://www.curseforge.com/minecraft/mc-mods/blame
And then reproduce the crash? After you get the crash to happen, please share the latest.log file with me here (it is in the logs folder above the mods folder).

Hopefully it will say exactly which structure is crashing as it does not appear to be my structure at all since my mod is not listed in the stacktrace. I suspect it is actually a vanilla structure that is crashing but we won't be able to debug why until we know which.

**Comment by LunafeyLazuli** [comment] 2021-06-15 23:16
Sure thing cause the last few times it's happened it always seems to be when genning new structures and this mod was the only structure genning mod that I updated recently

**Comment by LunafeyLazuli** [comment] 2021-06-15 23:42
Ah so come to find out, forgot that Ice and Fire updated and it's their graveyards that are causing the crash so I posted on their GitHub, but thank you for the mod! Helped loads

**Comment by TelepathicGrunt** [comment] 2021-06-15 23:50
Yeah it got reported here and they are doing a fix. https://github.com/Alex-the-666/Ice_and_Fire/issues/3950

I'll close this report then!

**Closed as completed by TelepathicGrunt** 2021-06-15 23:50 UTC
Labels: need more info
