### ISSUE TITLE
cannot invoke errors on forge 1.20.1

### ISSUE THREAD

**Issue by VaporeonScripts** [TelepathicGrunt/RepurposedStructures#363] opened 2024-12-18 16:37 UTC
https://mclo.gs/LGcyzTv

**Comment by VaporeonScripts** [comment] 2024-12-18 16:37
![image](https://github.com/user-attachments/assets/ed891549-4a9f-4e56-8a3b-794f4d0dffba)

**Comment by TelepathicGrunt** [comment] 2024-12-18 16:39
Mods passing null for entities to the trades is not valid and would’ve crashed vanilla iirc. I sorta remember a mod doing this and they had to be the one to fix the issue

**Comment by TelepathicGrunt** [comment] 2024-12-18 16:41
Yep duplicate of this:
https://github.com/TelepathicGrunt/RepurposedStructures/issues/346

Also please remove redirector. What they do is unsafe and if that one breaks my mod next, I won’t provide support

**Comment by VaporeonScripts** [comment] 2024-12-18 16:42
![image](https://github.com/user-attachments/assets/d493a4a7-b94f-498c-83f6-084cd46f9851)
could it be just enough resources btw?

**Closed as completed** 2024-12-18 16:42 UTC
Labels: duplicate
