### ISSUE TITLE
Data Pack validation failed

### ISSUE THREAD

**Issue by LPDawid** [TelepathicGrunt/RepurposedStructures#279] opened 2023-04-28 00:16 UTC
### Environment
Steam Deck, SteamOS 3.4.6, Prism Launcher 6.3 (flatpak stable), Fabric Loader 0.14.19,
Minecraft 1.19.3, Fabric API 0.76.1, MidnightLib 1.1, Cloth Config 9.0.94
Repurposed Structures 6.3.19, YUNG's API 3.9, YUNG's Better Nether Fortresses 1.1.1

Affected data pack: Repurposed Structures - Yung's Better Nether Fortress Compat v2-v4

No other mod, plugin, data pack, shader, resource pack loaded.

All downloaded from Modrinth.

### Reproduction
Create new world, drag and drop data pack (v2, v3 or v4), apply. Message "Data pack validation failed!" will show up.
or
Edit existing world, open world folder, add zip file there, save, play selected world. Message "Errors in currently selected datapacks prevented the world from loading." will show up. World loads just fine without it.

**There are no problems when using v1.**

[Log from both error scenarios with v4](https://github.com/TelepathicGrunt/RepurposedStructures/files/11348782/latest.log.txt)

**Comment by TelepathicGrunt** [comment] 2023-04-28 00:23
`Caused by: java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/structure_pool_element]: yungsapi:yung_feature_element`

Yung did not port yung_feature_element to 1.19.3+ yet. You would have to reach out to him. The datapack works just fine on 1.19.2 Yung API 
https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric/files/4441684
![image](https://user-images.githubusercontent.com/40846040/235019610-8c3bb5b8-1f1f-45f3-b2de-bff021d355f7.png)

**Comment by TelepathicGrunt** [comment] 2023-04-28 00:31
I just spoke with Yung. He ported the yung_feature_element to 1.19.4 while skipping 1.19.3. Since 1.19.3 is basically dead now, I would urge you to update to 1.19.4 where the datapack and mods should work just fine. Closing this since Yung and I are supporting only 1.19.2 and 1.19.4 right now.

**Closed as completed by TelepathicGrunt** 2023-04-28 00:31 UTC
Labels: Unsupported version

**Comment by LPDawid** [comment] 2023-04-28 00:39
Oh, I see. Shouldn't 1.19.3 label be removed from v2-v4 then? I will be migrating to 1.19.4 soon, still waiting for some mods to be updated.

**Comment by TelepathicGrunt** [comment] 2023-04-28 00:42
Label now removed for v2 to v4 of datapack
