### ISSUE TITLE
END PYRAMIDS EXPLODE IMMEDIATELY AFTER CHUNK IS LOADED

### ISSUE THREAD

**Issue by Camawama** [TelepathicGrunt/RepurposedStructures#256] opened 2023-01-18 06:23 UTC
It's easier for you to test it out on the modpack instead of installing every mod I have but something is causing the trap to activate early. This was tested on singleplayer and multiplayer.

**Comment by Camawama** [comment] 2023-01-18 06:25
this is the modpack the issue is happening on.

https://www.curseforge.com/minecraft/modpacks/vanilla-plus-by-cama/

**Comment by TelepathicGrunt** [comment] 2023-01-18 11:22
Duplicate of: https://github.com/TelepathicGrunt/RepurposedStructures/issues/215

The issue is lootr. You will need to edit their config to blacklist the end pyramid loot table so lootr does not replace the chest and trigger the trap. See the issue report I linked for more details on that

**Closed as completed by TelepathicGrunt** 2023-01-18 11:22 UTC
Labels: duplicate
