### ISSUE TITLE
Morewaterlogging mod breaks Repurposed Structure's Dark Forest Dungeon processor

### ISSUE THREAD

**Issue by BugmanBugman** [TelepathicGrunt/RepurposedStructures#95] opened 2021-05-16 06:39 UTC
https://gist.github.com/BugmanBugman/946b79cbb9c15c5a89b603bd57875846

**Comment by TelepathicGrunt** [comment] 2021-05-16 13:47
Please show me your full latest.log file. Someone's mod broke processors which then cascaded the error through all worldgen files and killed a lot of stuff from my mod. It could be that someone added a property unsafely to a block or has a broken processor in their mod. With out the full log and mod folder/profile, I cannot do anything to troubleshoot this.

**Comment by BugmanBugman** [comment] 2021-05-16 23:40
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/6490267/latest.log)

This was on a server by the way, so here's the mod list
https://gist.github.com/BugmanBugman/3e7fcf5a00057e864bed9ebe1239d7a5

**Comment by TelepathicGrunt** [comment] 2021-05-17 00:29
Found it. You have More Waterlogging on which is specifically causing this issue. I marked that mod as incompatible on my curseforge page and I hoped launchers would tell the user to not use it with my mod. Guess it doesn't do that lol.

I did reach out to the dev for More Waterlogging a while ago and said they are too busy to fix the issue due to them having like a million other mods and commissions to work on which is understandable. It does mean the bug won't be fixed on their end for a while. 

For now, you will have to either remove Repurposed Structures or remove More Waterlogging mod. Sorry there isn't more we can do.

I'll leave up this issue report so others may see this and know what the issue is when the Dark Forest Dungeon processor blows up for them as well.

**Comment by BugmanBugman** [comment] 2021-05-17 00:36
Ah ok, thanks for letting me know 😄
It works out since I was planning on removing MW already, since it's incompatible with another of my mods

**Comment by TelepathicGrunt** [comment] 2021-05-17 00:39
Oh I should explain why it breaks too so other people reading this can understand the situation.

More Waterlogging adds new properties to blocks to make waterlogging work for non-waterloggable blocks. However, the way they add the properties is dangerous and unsafe. 

My mod uses vanilla's worldgen datapack system for its structure processors. Some of these processors allow me to specify what block to randomly replace with another block. But the vanilla system is finky and requires me to specify every single property that a block has into the processor json files as well. If any property is missing, the processor blows up and vanilla cascades the failure through all my other processors and break them all along the way which results in dungeons that look incorrect and possibly villages not being randomized in their blocks correctly. 

Now when More Waterlogging adds a new waterlogging property to blocks unsafely, vanilla's worldgen datapack system looks at the vanilla blocks I specified in my processor, sees it is missing the waterlogging property in the json, and just self-destructs as a result. There are ways of adding properties to blocks in a safe way that does not break vanilla's worldgen datapack system but is is very tricky and complex to pull off. I know the mod [Towelette](https://github.com/Virtuoel/Towelette) on Fabric managed to add properties safely without blow up my mod. Hopefully when the More Waterlogging dev has time, he can ask the Towelette dev for how to add properties safely to vanilla blocks.

Hope that clears up the confusion!

**Comment by TelepathicGrunt** [comment] 2021-05-29 17:28
More waterlogging has been updated to use Statement library! Which means it now won't break my mod's processors anymore. Morewaterlogging-1.5 should be safe now! I'll close this report as they fixed the issue

**Closed by TelepathicGrunt** 2021-05-29 17:28 UTC
Labels: Mod Compat
