### ISSUE TITLE
When it is running with Valkyrienskies and its affiliates on the server, the server will freeze when the player passes through certain chunks

### ISSUE THREAD

**Issue by ghfth-djh** [TelepathicGrunt/RepurposedStructures#366] opened 2024-12-30 14:23 UTC
When it is running with Valkyrienskies and its affiliates on the server, the server will freeze when the player passes through certain chunks.

2024-12-30 19:15:55,732 DEBUG [Server thread] m.p.a.ArmourersWorkshop.debug(18): welcome back ghfth
2024-12-30 19:15:55,849 INFO  [Server thread] n.m.s.p.PlayerList.m_11261_(338): ghfth[/110.84.209.17:64572] logged in with entity id 597 at (-1056.8252489708725, 145.0, 123.13869010202988)
2024-12-30 19:15:56,181 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768126
2024-12-30 19:15:56,182 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753729 : 768127
2024-12-30 19:15:56,182 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768127
2024-12-30 19:15:56,183 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753727 : 768127
2024-12-30 19:15:56,183 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753729 : 768128
2024-12-30 19:15:56,183 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768128
2024-12-30 19:15:56,183 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753727 : 768128
2024-12-30 19:15:56,183 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(26): Watch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768129
2024-12-30 19:15:56,187 DEBUG [Server thread] o.v.c.i.s.zV.b(-1): 8a973470-38f0-490a-b4e4-d3c1659134da watched ships: [643]
2024-12-30 19:15:57,137 WARN  [Thread-55] o.v.c.i.s.Ax.a(-1): Ruby says "this should work just fine", lets hope it does 😂
2024-12-30 19:16:05,593 DEBUG [ftbbackups2_QuartzSchedulerThread] n.c.f.r.o.q.c.QuartzSchedulerThread.run(268): batch acquisition of 0 triggers
2024-12-30 19:16:09,600 DEBUG [Server thread] mixin.log(107): Mixing sequencedgearshift.InstructionAccessor from create_connected.mixins.json into com.simibubi.create.content.kinetics.transmission.sequencer.Instruction
2024-12-30 19:16:09,601 DEBUG [Server thread] mixin.log(107): create_connected.mixins.json:sequencedgearshift.InstructionAccessor: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
2024-12-30 19:16:09,601 DEBUG [Server thread] mixin.log(107): Mixing sequencedgearshift.InstructionMixin from create_connected.mixins.json into com.simibubi.create.content.kinetics.transmission.sequencer.Instruction
2024-12-30 19:16:09,601 DEBUG [Server thread] mixin.log(107): create_connected.mixins.json:sequencedgearshift.InstructionMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
2024-12-30 19:16:09,603 DEBUG [Server thread] mixin.log(107): Mixing sequencedgearshift.InstructionSpeedModifiersAccessor from create_connected.mixins.json into com.simibubi.create.content.kinetics.transmission.sequencer.InstructionSpeedModifiers
2024-12-30 19:16:09,603 DEBUG [Server thread] mixin.log(107): create_connected.mixins.json:sequencedgearshift.InstructionSpeedModifiersAccessor: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
2024-12-30 19:16:09,632 WARN  [Server thread] n.m.w.l.c.LevelChunk.m_142224_(779): Block entity sophisticatedbackpacks:backpack @ BlockPos{x=-1043, y=80, z=216} state Block{sophisticatedbackpacks:copper_backpack}[battery=false,facing=south,left_tank=false,right_tank=false,waterlogged=false] invalid for ticking:
2024-12-30 19:16:10,903 DEBUG [Server thread] mixin.log(107): Mixing ContraptionInvWrapperMixin from createutilities.mixins.json into com.simibubi.create.content.contraptions.Contraption$ContraptionInvWrapper
2024-12-30 19:16:17,654 WARN  [Server thread] n.m.s.MinecraftServer.m_130011_(843): Can't keep up! Is the server overloaded? Running 6699ms or 133 ticks behind
2024-12-30 19:16:20,011 WARN  [Server thread] n.m.w.e.EntityType.m_185999_(474): Skipping Entity with id betteranimalsplus:songbird
2024-12-30 19:16:29,018 DEBUG [ftbbackups2_QuartzSchedulerThread] n.c.f.r.o.q.c.QuartzSchedulerThread.run(268): batch acquisition of 0 triggers
2024-12-30 19:16:33,927 DEBUG [Server thread] sophisticatedcore.load(49): Compacting shapes not found in cache for "minecraft:flint" - querying recipes to get these
2024-12-30 19:16:33,928 WARN  [Server thread] futurepack.getPlayerFromImpl(221): Unable to determine player for class net.p3pp3rf1y.sophisticatedcore.util.RecipeHelper$3 (Examined Fields:[])
2024-12-30 19:16:34,022 DEBUG [Server thread] sophisticatedcore.load(49): Compacting shapes not found in cache for "cyclic:flint_block" - querying recipes to get these
2024-12-30 19:16:34,212 DEBUG [Server thread] n.m.f.l.FileUtils.getOrCreateDirectory(41): Found existing WildfireGender directory : E:\mc\EAPS1.0.14\config\WildfireGender
2024-12-30 19:16:35,423 DEBUG [Server thread] sophisticatedcore.load(49): Compacting shapes not found in cache for "minecraft:iron_nugget" - querying recipes to get these
2024-12-30 19:16:35,505 DEBUG [Server thread] sophisticatedcore.load(49): Compacting shapes not found in cache for "minecraft:iron_ingot" - querying recipes to get these
2024-12-30 19:16:38,698 DEBUG [Server thread] o.v.c.i.n.NetworkChannel.serverReceive(-1): Server received packet of type: PacketType(channel=org.valkyrienskies.core.impl.networking.NetworkChannel@7aeb50c5, id=1, name=SimplePacket - class org.valkyrienskies.core.impl.networking.impl.PacketRequestUdp)
2024-12-30 19:16:58,293 DEBUG [ftbbackups2_QuartzSchedulerThread] n.c.f.r.o.q.c.QuartzSchedulerThread.run(268): batch acquisition of 0 triggers
2024-12-30 19:17:02,340 INFO  [Server thread] n.m.s.n.ServerGamePacketListenerImpl.m_9957_(1721): ghfth issued server command: /tp -5406 75.5 -1985
2024-12-30 19:17:03,171 INFO  [Worker-Main-22] initial_house.log(12): [DEBUG:] Spawn Point is (-875, 0, 147).
2024-12-30 19:17:03,523 DEBUG [Worker-Main-21] mixin.log(107): Mixing JigsawPlacementMixin from waystones.mixins.json into net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement$Placer
2024-12-30 19:17:03,523 DEBUG [Worker-Main-21] mixin.log(107): Renaming synthetic method lambda$getShuffledTemplates$2(Lnet/minecraft/world/level/levelgen/structure/pools/StructurePoolElement;)Z to md62a234$lambda$getShuffledTemplates$2$0 in waystones.mixins.json:JigsawPlacementMixin
2024-12-30 19:17:03,526 DEBUG [Worker-Main-21] mixin.log(107): Renaming synthetic method lambda$getShuffledTemplates$1(Ljava/lang/String;)Z to md62a234$lambda$getShuffledTemplates$1$1 in waystones.mixins.json:JigsawPlacementMixin
2024-12-30 19:17:03,526 DEBUG [Worker-Main-21] mixin.log(107): Renaming synthetic method lambda$getShuffledTemplates$0(Ljava/lang/Object;)Ljava/lang/String; to md62a234$lambda$getShuffledTemplates$0$2 in waystones.mixins.json:JigsawPlacementMixin
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753729 : 768127
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753729 : 768128
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768126
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768127
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768128
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753727 : 768127
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753728 : 768129
2024-12-30 19:17:03,628 DEBUG [Server thread] o.v.m.c.w.ChunkManagement.tickChunkLoading(52): Unwatch task for dimension minecraft:dimension:minecraft:overworld: -1753727 : 768128
2024-12-30 19:17:03,655 DEBUG [Server thread] o.v.c.i.s.zV.a(-1): 8a973470-38f0-490a-b4e4-d3c1659134da unwatched ships [643]
2024-12-30 19:17:11,008 INFO  [Server thread] n.m.s.n.ServerGamePacketListenerImpl.m_9957_(1721): ghfth issued server command: /ftblibrary gamemode
2024-12-30 19:17:13,132 DEBUG [Worker-Main-30] mixin.log(107): Mixing WorldGenRegionAccessor from habitat.mixins.json into net.minecraft.server.level.WorldGenRegion
2024-12-30 19:17:13,132 DEBUG [Worker-Main-30] mixin.log(107): Mixing world.WorldGenRegionAccessor from repurposed_structures.mixins.json into net.minecraft.server.level.WorldGenRegion
2024-12-30 19:17:13,132 DEBUG [Worker-Main-30] mixin.log(107): Mixing MuteSetBlockFarChunk from iceandfire.mixins.json into net.minecraft.server.level.WorldGenRegion
2024-12-30 19:17:13,133 DEBUG [Worker-Main-30] mixin.debug(67): Unexpected: Registered method getStructureFeatureManager()Lnet/minecraft/world/level/StructureFeatureManager; in net.minecraft.server.level.WorldGenRegion was not merged
2024-12-30 19:17:13,145 DEBUG [Worker-Main-25] mixin.log(107): Mixing BeardifierMixin from yungsapi.mixins.json into net.minecraft.world.level.levelgen.Beardifier
2024-12-30 19:17:13,355 DEBUG [Worker-Main-28] mixin.log(107): Mixing SurfaceRulesContextMixin from blueprint.mixins.json into net.minecraft.world.level.levelgen.SurfaceRules$Context
2024-12-30 19:17:13,355 DEBUG [Worker-Main-28] mixin.log(107): Renaming synthetic method lambda$updateModdedBiomeSlice$0(Lcom/teamabnormals/blueprint/common/world/modification/ModdedBiomeSource;III)Lnet/minecraft/resources/ResourceLocation; to md62a234$lambda$updateModdedBiomeSlice$0$0 in blueprint.mixins.json:SurfaceRulesContextMixin
2024-12-30 19:17:14,449 INFO  [Server thread] n.m.s.n.ServerGamePacketListenerImpl.m_9957_(1721): ghfth issued server command: /gamemode spectator
2024-12-30 19:17:24,609 WARN  [Physics thread] o.v.c.i.s.Ak.a(-1): Too many physics frames in the physics frame queue. Is the game stage broken?
2024-12-30 19:17:25,612 WARN  [Physics thread] o.v.c.i.s.Ak.a(-1): Too many physics frames in the physics frame queue. Is the game stage broken?
2024-12-30 19:17:26,614 WARN  [Physics thread] o.v.c.i.s.Ak.a(-1): Too many physics frames in the physics frame queue. Is the game stage broken?
2024-12-30 19:17:27,615 WARN  [Physics thread] o.v.c.i.s.Ak.a(-1): Too many physics frames in the physics frame queue. Is the game stage broken?
2024-12-30 19:17:27,921 DEBUG [ftbbackups2_QuartzSchedulerThread] n.c.f.r.o.q.c.QuartzSchedulerThread.run(268): batch acquisition of 0 triggers

**Comment by TelepathicGrunt** [comment] 2024-12-30 14:28
Three questions.

- What minecraft version and modloader? I develop for multiple versions and loaders so not providing this info in any issue report is painful for me.
  
- Have you tried doing a thread dump when the server is frozen? The thread dump will show exactly what code the game is stuck on.

- Is there any specific reason for why you think my mod is involved with the issue? The log snippet you provided has no useful info about the issue and is just regular startup. Log snippets are not helpful as opposed to full logs. though in this case, you need to do a thread dump instead.

**Comment by ghfth-djh** [comment] 2024-12-30 14:47
minecraft version=1.18.2
modloader=forge40.2.17
Servercore=mohist-1.18.2-181
thread dump couldn apply since the sever didn actually crash ，instead it will repeat this （ WARN [Physics thread] o.v.c.i.s.Ak.a(-1): Too many physics frames in the physics frame queue. Is the game stage broken? ）
i could only get these four file
[latest.log](https://github.com/user-attachments/files/18275489/latest.log)
[FP-Latest.log](https://github.com/user-attachments/files/18275490/FP-Latest.log)
[debug.log](https://github.com/user-attachments/files/18275491/debug.log)
[crafttweaker.log](https://github.com/user-attachments/files/18275493/crafttweaker.log)

**Comment by ghfth-djh** [comment] 2024-12-30 14:52
And the reason I think repurposed_structures is causing this problem is because I no have this issue after removing it

**Comment by TelepathicGrunt** [comment] 2024-12-30 14:59
First, thread dumps are done while the game is running. You do not need to crash to get a thread dump. Ask your server host to do a  thread dump if you need to do so or if you own the server, use visualvm, attach it, and do a thread dump.

Second, mohist is a bad attempt at combining forge and plugins. These hybrid servers are always janky and breaking mods. I will not provide any support for these as they often break forge patches or events or worse.

Third, anytime people blamed repurposed structures for a freeze, I always get a thread dump and just about every time, it is never repurposed structure's fault. Usually caused by other mods shoving in ServerLevel calls within worldgen and then deadlocks the game by causing the generating chunk to wait on itself. Sometimes these mods do the unsafe code on certain entity spawns and when said entity spawns in a structure, that causes the issue. Not the fault of the mod having the entity in the structure but the fault of the mod injecting the bad code. Especially as with a datapack, anyone can add any entity to spawn in a structure.

Closing this not only do I not support 1.18.2, but mohist involved automatically makes this impossible for me to reproduce and invalidates this issue report. If the issue can be reproduce with a normal forge install, then I can help read the thread dump if you can get one and show you which mod is calling unsafe code during worldgen

**Closed as completed by TelepathicGrunt** 2024-12-30 14:59 UTC
Labels: Unsupported version

**Comment by ghfth-djh** [comment] 2024-12-30 16:11
wow，this problem did cause by mohish，after i redeploy to forge-end the problem solve and the tick were much them mohish-end∑(O_O；)
