### ISSUE TITLE
villigers plus logspam 

### ISSUE THREAD

**Issue by marchiggs** [TelepathicGrunt/RepurposedStructures#357] opened 2024-10-16 00:09 UTC
[01:03:51] [Worker-Main-764/WARN]: Repurposed Structures: Non-existent child pool attempted to be spawned: minecraft: which is being called from villagersplus:villages/bamboo/horticulturist. Let Repurposed Structures dev (TelepathicGrunt) know about this log entry.

**Comment by TelepathicGrunt** [comment] 2024-10-16 01:10
I need more info. Like what mc version, modloader, and datapack version are you using for that compat datapack

**Comment by marchiggs** [comment] 2024-10-17 12:15
1.20.1  im using Multi Mc V5 and version 7.1.15 of RS

**Comment by TelepathicGrunt** [comment] 2024-10-17 12:21
MultiMC is the mod launcher. I mean mod loader like forge or fabric.

**Comment by TelepathicGrunt** [comment] 2024-10-18 16:22
I am looking at the bamboo horticultruist file in Repurposed_Structures-VillagersPlus_v3.zip datapack and it only has 2 jigsaw blocks and neither of them are targeting just `minecraft:` as the pool. Testing in game myself, I do not get any logspam about it.
![image](https://github.com/user-attachments/assets/0da4e7eb-de59-4b6d-9a60-983a8aa536e5)
![image](https://github.com/user-attachments/assets/a3637a1a-0220-4eb7-87c5-99079d247aad)

Make sure the datapack you are using is indeed v3 and not an outdated version of the ddatapack

**Comment by TelepathicGrunt** [comment] 2024-10-25 12:56
closing as it has been a week with no new info and I cannot reproduce issue

**Closed as completed by TelepathicGrunt** 2024-10-25 12:56 UTC
Labels: need more info
