### ISSUE TITLE
[1.16.1] Server freezes when some structures generate with Hanami installed

### ISSUE THREAD

**Issue by TonDar0n** [TelepathicGrunt/RepurposedStructures#39] opened 2020-12-20 06:08 UTC
I don't really know why this is happening and you might have already fixed the issue in a more recent version of the mod (if the problem is with your mod I don't really know). My server was randomly freezing when I was generating new terrain, at the beginning I just made new worlds but the problem was persisting so I decided to investigate. On the last world i made the server was freezing when a mineshaft was being generated, the only mod that seems to cause this problem with yours is Hanami. You can find a screenshot of the barely generated mineshaft plus my modpack in the link bellow in case you want to look a the issue. Have a good day thanks for your mod !

https://drive.google.com/drive/folders/1iEE4Q-eESmKQVKxk7kQ9iznBVOny272O?usp=sharing

**Comment by TelepathicGrunt** [comment] 2020-12-20 06:12
I am not supporting any Mc version older than 1.16.2 as it’s too much work to maintain multiple Mc versions of my mods. 

Though I can take a quick look tomorrow and see if I can let you know what the freeze is caused by so you can see about a workaround before I close this issue.

**Comment by TonDar0n** [comment] 2020-12-20 11:40
Hi, sooo I've done some more tests and I was completely wrong your mod wasn't involved at all and as it turns out it appears that Druidcraft was the only mod causing problems. I don't know why removing Hanami helped for a brief moment but yeah.. I shouldn't open issues in the middle of the night lmao. I'm sorry I bothered you for nothing, have a good day !

**Comment by TelepathicGrunt** [comment] 2020-12-20 12:35
ah, glad you were able to figure out the issue! I'll close this report then

**Closed by TelepathicGrunt** 2020-12-20 12:35 UTC
Labels: Mod Compat, Unsupported version
