### ISSUE TITLE
Crash when generating a stronghold

### ISSUE THREAD

**Issue by cybercat5555** [TelepathicGrunt/RepurposedStructures#2] opened 2020-03-23 03:33 UTC
Forge 31.1.1
Repurposed Structures 1.2.1

When exploring out, a stronghold tried to generate, but it caused this crash. The world can be re-entered, but getting in the general area of the stronghold causes this crash.
[crash-2020-03-22_23.19.44-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/4367055/crash-2020-03-22_23.19.44-server.txt)

**Comment by TelepathicGrunt** [comment] 2020-03-23 12:45
Try turning on “useVanillaStronghold” config. I think I know how to fix it but see if that config fixes the issue for you temporarily so you can enter the world.

**Comment by TelepathicGrunt** [comment] 2020-03-23 14:14
I wasn't able to reproduce the crash even though it looks like it happens when trying to use the modded Stronghold in a world with a partially made Vanilla Stronghold. Either way, would you be able to test this .jar with a patch I made and see if that fixes the crash? If it works, I'll post it onto CurseForge. (Make sure you turn off useVanillaStronghold config when testing the patch)
[repurposedstructures-1.15.2-1.2.2b.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/4369863/repurposedstructures-1.15.2-1.2.2b.zip)

Sorry about that crash and hopefully this fixes it!

**Comment by mjlmjl888** [comment] 2020-03-23 21:07
I've had a similar problem.
[crash-2020-03-23_17.03.39-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/4371911/crash-2020-03-23_17.03.39-server.txt)

**Comment by TelepathicGrunt** [comment] 2020-03-23 21:09
@mjlmjl888 Yes please try the patch. I just need to make sure the patch does work and that i addressed the issue correctly. If it still crashes, please give me the new crash result. Thanks!

**Comment by mjlmjl888** [comment] 2020-03-23 21:10
Will do!

**Comment by mjlmjl888** [comment] 2020-03-23 21:20
I teleported to a stronghold using /locate and it did not crash.

**Comment by TelepathicGrunt** [comment] 2020-03-23 21:24
Awesome! Thank you both for reporting this crash! v1.2.2 should be approved shortly on curseforge with the patch. I'll close this issue report now :)

**Closed by TelepathicGrunt** 2020-03-23 21:24 UTC
Labels: bug
