### ISSUE TITLE
Yung's Better Stronghold support

### ISSUE THREAD

**Issue by maicol07** [TelepathicGrunt/RepurposedStructures#87] opened 2021-04-29 10:17 UTC
If Repurposed structures and Better Stronghold are installed, there isn't any stronghold in the world.

Better stronghold CF page: https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds

**Comment by TelepathicGrunt** [comment] 2021-04-29 12:01
When Better Strongholds is on Repurposed Structures stops spawning its own StoneBrick Stronghold and let Better Strongholds have full control.

if you are trying to /locate vanilla or repurposed structure’s Stonebrick stronghold, it will fail. You need to do /locate betterstrongholds:stronghold. Eyes of ender should go to their strongholds as well. Please test this and see if that is the case

**Comment by maicol07** [comment] 2021-04-29 13:46
Tried the locate command with betterstrongholds:stronghold but returns Can't find any structure near you.

Tried eyes of ender but points indefinitely to a direction without an end

**Comment by TelepathicGrunt** [comment] 2021-04-29 14:02
can you send me your world and modlist? this sounds like a bug interfering. 
Also, double check to make sure you are using the latest repurposed structures and latest better strongholds.

**Comment by maicol07** [comment] 2021-04-29 14:12
I have the latest version of the two mods.

Here you go:

World: https://share.maicol07.it/kOfI5/GevOsAZa49.zip

Mod list:

```
AkashicTome-1.4-16.jar                             car-1.16.5-1.0.3.jar
Apotheosis-1.16.4-4.5.2.jar                        carryon-1.16.5-1.15.3.13.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar                charginggadgets-1.3.0.jar
AutoRegLib-1.6-47.jar                              chocolate-1.3.0-1.16.4.jar
Babel-1.0.5.jar                                    cloth-config-4.11.19-forge.jar
BackTools-1.16.5-10.1.0.jar                        collective-1.16.5-2.26.jar
BetterBurning-1.16.5-6.0.3.jar                     comforts-forge-1.16.4-4.0.1.0.jar
BetterCaves-Forge-1.16.4-1.1.1.jar                 craftingstation-4.1.1.jar
BetterMineshafts-Forge-1.16.4-2.0.3.jar            decorative_blocks-1.16.4-1.7.2.jar
BetterPortals-1.16.4-0.3.2.jar                     dropthemeat-1.16.3-1.2.jar
BetterStrongholds-1.16.4-1.0.1.jar                 dungeons_plus-1.16.5-1.1.4.jar
BiomesOPlenty-1.16.5-13.1.0.458-universal.jar      dungeonsarise1.16.4-1.2.61a.jar
Bookshelf-1.16.5-10.0.7.jar                        easy_villagers-1.16.5-1.0.4.jar
BotanyPots-1.16.5-7.0.17.jar                       embellishcraft-1.16.4-3.3.0.0.jar
BotanyTrees-1.16.5-3.0.5.jar                       embellishcraft-bop-1.16.4-3.3.0.jar
BowInfinityFix-1.16.x-rv9.1.jar                    endercompass-1.5-1.16.4.jar
'CAC MOD [1.16.4-5] [2021.1].jar'                   endergetic-1.16.4-3.0.0.jar
'CACADD MOD [1.16.4-5] [2021.1].jar.disabled'       extradisks-1.16.4-1.5.0.jar
Chlorine-1.16.5-0.0.1.3.jar.disabled               fairylights-4.0.5-1.16.5.jar
Clumps-6.0.0.21.jar                                ferritecore-2.0.4-forge.jar
CodeChickenLib-1.16.4-3.5.1.408-universal.jar      findme-1.16.3-2.1.0.0.jar
Coins-1.16.5-6.0.2.jar                             ftb-backups-2.1.1.6.jar
Controlling-7.0.0.15.jar                           ftb-chunks-1605.2.3-build.75.jar
CraftingTweaks_1.16.3-12.2.0.jar                   ftb-gui-library-1605.2.1.41-forge.jar
Cucumber-1.16.4-4.1.9.jar                          ftb-quests-1605.2.1-build.39-forge.jar
'DataFixerSlayer 1.0-3.jar'                         ftb-ranks-1604.1.1.11.jar
DoggyTalents-1.16.4-2.0.1.3.jar                    ftb-ultimine-1605.2.0-build.26-forge.jar
DungeonCrawl-1.16.3-2.2.4.jar                      geckolib-forge-1.16.5-3.0.32.jar
DungeonsMod-1.16.3-1.3.15.jar                      gemsnjewels-1.16.4-0.21.0.jar
DynamicSurroundings-1.16.4-4.0.3.12.jar.disabled   giacomos_exp1.3-1.16.3.jar
EnchantmentDescriptions-1.16.5-7.0.8.jar           giacomos_fishing_net1.7.1-1.16.3.jar
EnderStorage-1.16.4-2.7.1.166-universal.jar        guardvillagers-1.16.5.1.2.4.jar
FastFurnace-1.16.4-4.4.0.jar                       iChunUtil-1.16.5-10.2.0.jar
FastLeafDecay-v25.jar                              invtweaks-1.16.4-1.0.1.jar
FastWorkbench-1.16.4-4.5.1.jar                     ironchest-1.16.4-11.2.10.jar
FpsReducer-mc1.16.5-1.19.jar                       ironfurnaces-1.16.5-2.6.6.jar
GameMenuModOption-1.16.4-1.8.jar                   item-filters-1605.2.4-build.30-forge.jar
JAOPCA-1.16.5-3.4.0.6.jar                          jei-1.16.4-7.6.1.71.jar
JEPB-1.0.0.jar                                     jeiintegration_1.16.5-7.0.1.15.jar
Jade-1.16.4-2.6.2.jar                              journeymap-1.16.5-5.7.1.jar
JustEnoughProfessions-1.16.5-1.2.1.jar             justenoughbeacons-3.1-1.16.3.jar
JustEnoughResources-1.16.4-0.12.0.107.jar          mapperbase-1.16.4-2.3.0.0.jar
KleeSlabs_1.16.5-9.2.1.jar                         mcw-bridges-1.0.5-mc1.16.5-4.jar
Lollipop-1.16.5-3.2.9.jar                          mcw-doors-1.0.2-mc1.16.5.jar
MixinBootstrap-1.0.5.jar                           mcw-fences-1.0.0-mc1.16.5.jar
Morpheus-1.16.5-4.2.70.jar                         mcw-furniture-2.0.1-mc1.16.5.jar
MouseTweaks-2.14-mc1.16.2.jar                      mcw-roofs-2.0.1-mc1.16.5-4.jar
MysticalAdaptations-1.16.4-1.1.1.jar               mcw-trapdoors-1.0.2-mc1.16.5.jar
MysticalAgradditions-1.16.4-4.1.5.jar              mcw-windows-1.0.3-mc1.16.5.jar
MysticalAgriculture-1.16.4-4.1.7.jar               minecolonies-0.14.97-ALPHA-universal.jar
NaturesCompass-1.16.5-1.8.6.jar                    mining_helmet-1.16.5-2.0.1.jar
NetherPortalFix_1.16.3-7.2.1.jar                   mininggadgets-1.7.5.jar
PackingTape-1.16.3-0.10.0.jar                      outvoted-1.16.5-1.2.4.jar
PickleTweaks-1.16.4-5.2.2.jar                      overloadedarmorbar-5.1.0.jar
Placebo-1.16.4-4.4.2.jar                           pamhc2foodcore-1.16.3-1.0.2.jar
Powah-1.16.5-2.3.16.jar                            pamhc2trees-1.16.3-1.0.1.jar
Quark-r2.4-311.jar                                 performant-1.16.2-5-3.54m.jar
QuarkOddities-1.16.3.jar                           plane-1.16.5-1.0.0.jar
SereneSeasons-1.16.5-4.0.1.91-universal.jar        polymorph-forge-1.16.5-0.24.jar
SimplyJetpacks2-1.16.5-2.6.7.1.jar                 preview_OptiFine_1.16.5_HD_U_G8_pre12.jar
SpartanShields-1.16.4-2.1.1.jar                    randompatches-2.4.4-forge.jar
SpawnerFix-1.16.2-1.0.0.2.jar                      refinedstorage-1.9.12.jar
StorageDrawers-1.16.3-8.2.2.jar                    reliquary-1.16.5-1.3.5.1098.jar.disabled
Toast-Control-1.16.4-4.3.1.jar                     repurposed_structures-1.16.5-2.6.5-forge.jar
ToolStats-1.16.5-6.0.1.jar                         scuba-gear-1.16.5-1.0.3.jar
Waddles-1.16.5-0.8.12.jar                          softerhaybales_1.16.5-1.3.jar
Waystones_1.16.5-7.4.0.jar                         solcarrot-1.16.3-1.9.10.jar
Wither-Skeleton-Tweaks-1.16.4-5.3.0.jar            spark-forge.jar
YungsApi-1.16.4-Forge-6.jar                        structure_gel-1.16.5-1.7.7.jar
abnormals_core-1.16.5-3.1.1.jar                    structurize-0.13.163-ALPHA-universal.jar
absentbydesign-1.16.5-1.4.1.jar                    swingthroughgrass-1.16.4-1.5.3.jar
adaptive_performance_tweaks_1.16.5-0.4.3.jar       tombstone-1.16-6.3.4.jar
architectury-1.12.145-forge.jar                    torchmaster-2.3.7.jar
betteranimals-1.16.4-5.5.0.jar                     tumbleweed-1.16-0.4.9.jar
betteranimalsplus-1.16.5-10.2.0.jar                u_team_core-1.16.5-3.2.1.195.jar
betterweather-1.2.9.jar                            useful_backpacks-1.16.5-1.12.0.89.jar
buildersaddition-1.16.5-20210421a.jar              valhelsia_structures-16.0.5.jar
buildinggadgets-1.16.5-3.8.0.jar                   villagerdeathmessages_1.16.5-1.8.jar
byg-1.2.jar                                        villagernames_1.16.5-2.9.jar
cagedmobs-1.16.5-1.3.2.jar                         xptome-1.16.5-v2.1.jar
callablehorses-1.16.3-1.2.1.4.jar
```

**Comment by TelepathicGrunt** [comment] 2021-04-29 14:29
Sorry, I should've been more clear. Can you export the mods themselves or modpack so i can download it? individually downloading all the mods manually takes me forever lol.

though i just tried with better strongholds and repurposed structures alone and it is working for me
![image](https://user-images.githubusercontent.com/40846040/116567566-be59f900-a8d5-11eb-8233-3ea2fdd72a42.png)

**Comment by maicol07** [comment] 2021-04-29 16:29
Here it is, sorry for the wait: s[hare.maicol07.it/kOfI5/HobiRihA93.zip](https://share.maicol07.it/kOfI5/HobiRihA93.zip)

**Comment by TelepathicGrunt** [comment] 2021-04-30 12:05
Question, when you were testing, were you testing in singleplayer or on server? Several people are reporting that better strongholds isnt working on server and many of them do not have repurposed structures on. Gonna close this as this isn't actually related to repurposed structures. Still, i'm trying to collect info to help yung

**Closed by TelepathicGrunt** 2021-04-30 12:05 UTC
Labels: Another mod's issue

**Comment by maicol07** [comment] 2021-04-30 12:06
@TelepathicGrunt singleplayer

**Comment by TelepathicGrunt** [comment] 2021-04-30 12:13
I put on Better Strongholds into the modpack you gave and locate is working and the stronghold is spawning. Try deleting Better Stronghold's config from your config folder to see if the issue is caused by a broken config file. Idk what the issue is but it has to be due to your modpack's world or other folders like configs. weird 
![image](https://user-images.githubusercontent.com/40846040/116693285-aba1fb80-a98b-11eb-99d4-55347112137a.png)

**Comment by maicol07** [comment] 2021-05-08 09:43
@TelepathicGrunt I tried to update all the mods to the latest version and recreate a world and it seems working now!
