### ISSUE TITLE
biomes o plenty/terraforged compatability

### ISSUE THREAD

**Issue by kian2001** [TelepathicGrunt/RepurposedStructures#120] opened 2021-07-28 12:14 UTC
i just added this mod into my already existing world and loaded up some new chunks and couldn't find any structures I'm wondering if its compatible with biomes o plenty and terraforged

**Comment by TelepathicGrunt** [comment] 2021-07-28 12:26
This mod is compatible with bop and people have reported it works with terraforged. I'm gonna need more info before I can even know where to begin with troubleshooting lol.

Can you put on this mod called Blame? https://www.curseforge.com/minecraft/mc-mods/blame
Then enter the world. Do /locate village_giant_tree_taiga and teleport to it.
Now go into the logs folder above the mods folder and drag the latest.log file onto this issue report and post it here. That way I can see all the info and maybe see what the problem is

**Comment by TelepathicGrunt** [comment] 2021-08-02 18:10
Were you able to get more info? Or did you figure out the issue by now?

**Comment by TelepathicGrunt** [comment] 2021-08-10 00:47
It's been 13 days and no additional info was provided. I cant really do anything so I'll close this report. Just post your latest.log here and I'll reopen this report.

**Closed as completed by TelepathicGrunt** 2021-08-10 00:47 UTC
Labels: need more info
