### ISSUE TITLE
1.18.2 "Feature Placement" Crash when loading a chunk in the Nether

### ISSUE THREAD

**Issue by Fade-Alchemist** [TelepathicGrunt/RepurposedStructures#262] opened 2023-02-18 23:57 UTC
I am approaching a Nether Temple and as it loads in the game crashes. I have a few Crash Logs attached to provide an example.  This is Fabric 1.18.2 

[crash-2023-02-19_00.51.33-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/10775402/crash-2023-02-19_00.51.33-server.txt)
[crash-2023-02-18_20.19.34-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/10775403/crash-2023-02-18_20.19.34-server.txt)
[crash-2023-02-18_20.11.24-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/10775404/crash-2023-02-18_20.11.24-server.txt)

**Comment by TelepathicGrunt** [comment] 2023-02-19 01:14
Duplicate of https://github.com/TelepathicGrunt/RepurposedStructures/issues/220

short summary, you’re trying to use a world made in 1.18.1 or older Mc with older repurposed structures and the game dies in newer version because a chunk in partial generation is still trying to reference old structure info that no longer exists.  

Use the datapack here to create dummy version of the data it is looking for and stop the crash. https://github.com/TelepathicGrunt/RepurposedStructures-Quilt/issues/199#issuecomment-1132217839

Updating modpacks across major Mc versions tends to always cause issues. Some more problematic than others like this

**Closed as completed by TelepathicGrunt** 2023-02-19 01:14 UTC
Labels: duplicate, Unsupported version
