### ISSUE TITLE
Broken 'RS Abnormals + Farmers Delight Compat' datapack crashes RS Flower Forest Pyramids (Fixed datapack inside this report)

### ISSUE THREAD

**Issue by Not-February** [TelepathicGrunt/RepurposedStructures#126] opened 2021-08-09 00:24 UTC
``Forge 36.2.0``
``Repurposed Structures 3.0.4``

Other mods _are_ installed, if you're having trouble reproducing the issue I can provide a full mod list.

Crash Log: https://gist.github.com/Febilian/b6331e2791319c8ae27016c422cb950f
Full Server Log: https://gist.github.com/Febilian/4da74f2791bcea994f3586081f2fb8bb

**Comment by TelepathicGrunt** [comment] 2021-08-09 00:27
can you put on the mod called Blame, start up the world, and then give me the latest.log file? 
https://www.curseforge.com/minecraft/mc-mods/blame

The crash you have is when the start pool for a structure is nuked to be empty. This tends to happen when a mod adds a property unsafely to vanilla blocks which then break the parsing of my structure processor. Minecraft takes that error and nukes the pool files which leads to that crash

**Comment by Not-February** [comment] 2021-08-09 00:39
A player tested the same world in single player and reproduced the same crash with Blame installed. Here you go, their latest.log:

https://gist.github.com/Febilian/46e7769bd9ea55c49bf2a23ed9d13a33

**Comment by TelepathicGrunt** [comment] 2021-08-09 00:45
Ah you are using the RS Environmental Datapack that is broken and causes Flower Forests to crash because it forgot to have block properties stated for some of the processors. I made a PR to fix the datapack but you can download the fixed version from here while you wait: https://gitlab.com/pm065/RepurposedRepurposedStructures/-/merge_requests/1#note_645821914

I'm gonna leave up this issue report for others to see until my PR is merged and the REFORM modpack releases with the fixed datapack.

Fixed datapack to use: 
[RS_Abnormals_+_Farmers_Delight_Compat_Fixed.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/6951712/RS_Abnormals_%2B_Farmers_Delight_Compat_Fixed.zip)

**Comment by Not-February** [comment] 2021-08-09 00:46
Oh, we are indeed - that would explain things. I'll use the fixed one, thanks!

**Comment by Wedge1453** [comment] 2021-08-10 07:52
fixed, REFORM has been updated, thank you for your help, you can close the issue now.

**Comment by TelepathicGrunt** [comment] 2021-10-04 00:15
Closing this issue report now as it turns out that pm095 archived their datapack repo and stopped working on the datapacks. So I downloaded their datapacks and now host them on my repo here: https://github.com/TelepathicGrunt/RepurposedStructures/releases

The Environmental changes pm095 did in one datapack is now merged into my Repurposed_Structures-Environmental datapack. The other two datapacks are Repurposed_Structures-Buzzier_Bees and Repurposed_Structures-Farmers_Delight which are now listed separately

I did fixed the issue with the environmental portion from pm095 that was the cause of this bug report so these datapacks I host myself should be safe and will be maintained by me going forward instead of being abandoned.

**Closed as completed by TelepathicGrunt** 2021-10-04 00:15 UTC
Labels: bug, duplicate
