### ISSUE TITLE
Crash with TreeChop 0.14.1 (update it to 0.14.5 to fix crash)

### ISSUE THREAD

**Issue by Krampus69** [TelepathicGrunt/RepurposedStructures#144] opened 2021-09-29 14:02 UTC
Hello :wave:
Had a weird crash while ingame lately.

Here is my debug & my latest.log :
[logs.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/7252509/logs.zip)
 
I was in a cold biome temple when I made the traps inside explode, then it crashed.
The logs said it was because of a mineshaft piece that couldn't be found in some pool. I'm not sure how this works.

Also, I have BOP/ByG/Better Mineshafts so might be one of the reasons why there is so much log spam

Thank you for your help :)

**Comment by TelepathicGrunt** [comment] 2021-09-29 14:28
Can you send me your mod list? (if possible, you can export your modpack from curseforge launcher so I can download all the mods instantly. Else, zipping up all the mods and sharing that with me will greatly help but I can still work with a modlist) 

It seems something in the modpack is killing many pool files in my mod which in turn, crashes some mineshafts or stuff. Also, share your config files for repurposed structures so I can double check that too.

**Comment by Krampus69** [comment] 2021-09-29 17:04
Here you go : 
https://we.tl/t-ggNFfcecEF

**Comment by TelepathicGrunt** [comment] 2021-09-30 23:55
Sorry about the delay. I got carried away by other stuff but after testing and looking closer at logs, I believe the issue is you are using an older version of TreeChop (0.14.1). It is classloading TagCollectionManager too early which breaks other mods who try to bind their tags in code afterwards. 
https://paste.ee/p/ISNEr

One of these mods trying to bind a tag is End Remastered which uses their endrem:end_crystal_gen tag in one of their worldgen configuredfeature. But since the tag was broken by TreeChop, the configuredfeature is failed to be parsed. And this error cascades through other mod's features including repurposed structures and kills my mod as a result too.

Update TreeChop from 0.14.1 to 0.14.5 and the error/crash should go away. 

Log with TreeChop 0.14.1, Harder Spawners, End Remastered, Repurposed Structures, and Blame:
https://paste.ee/p/LXtFk

Log with TreeChop 0.14.5:
https://paste.ee/p/8BKR2

i hope this helps!

**Comment by TelepathicGrunt** [comment] 2021-09-30 23:57
Ah yeah, it was fixed in 0.14.3 treeChop as shown in this issue report. https://github.com/hammertater/treechop/issues/72

I'll close this report now since updating TreeChop will fix the issue you have definitely. If you get a new crash or issue with Repurposed Structures, you can open a new issue report as it will be caused by something else.

**Closed as completed by TelepathicGrunt** 2021-09-30 23:57 UTC
Labels: Mod Compat
